export const Data = {
  Notes: [
    {
      id: "1",
      title: "Amish",
      body: "Amish data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "2",
      title: "Mishra",
      body: "Mishra data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "3",
      title: "test",
      body: "test data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "4",
      title: "abcd",
      body: "efgh",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "5",
      title: "Untitled",
      body: "Untitled",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
  ],
};
