export const Data = {
  Notes: [
    {
      id: "01",
      title: "Amish",
      body: "Amish data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "02",
      title: "Mishra",
      body: "Mishra data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "03",
      title: "test",
      body: "test data",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "04",
      title: "abcd",
      body: "efgh",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
    {
      id: "05",
      title: "Untitled",
      body: "Untitled",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      innerNotes: [],
      inTrash: false,
    },
  ],
};
